Repository ASFHyP3/hyp3-gamma, pull requests merged in 2020-07, with the labels that each got.

#118 Organizational updates
  .github/pull_request_template.md
  .github/workflows/release.yml
  .github/workflows/test-and-build.yml
  CHANGELOG.md
  Dockerfile
  setup.py
Labels: CI/CD, documentation

#120 Release: add browse images to s3
  .github/pull_request_template.md
  .github/workflows/release.yml
  .github/workflows/test-and-build.yml
  CHANGELOG.md
  Dockerfile
  conda-env.yml
  hyp3_rtc_gamma/__main__.py
  hyp3_rtc_gamma/create_metadata.py
  hyp3_rtc_gamma/etc/README_RTC_GAMMA.txt
  hyp3_rtc_gamma/etc/RTC_GAMMA_Template_color_png.xml
  hyp3_rtc_gamma/etc/RTC_GAMMA_Template_grayscale_png.xml
  hyp3_rtc_gamma/rtc_sentinel.py
  setup.py
Labels: enhancement, patch

#122 Release: thumbnail images for hyp3 v2
  CHANGELOG.md
  hyp3_rtc_gamma/__main__.py
  tests/conftest.py
  tests/data/test.png
  tests/test_v2.py
Labels: enhancement, patch

#124 Release: thumbnail filename fix
  CHANGELOG.md
  hyp3_rtc_gamma/__main__.py
  tests/test_v2.py
Labels: bug, patch

#130 Don't duplicate conda channels and use conda hyp3lib
  .github/workflows/test-and-build.yml
  conda-env.yml
  setup.py
Labels: CI/CD

#132 Sync with templates README
  hyp3_rtc_gamma/etc/README_RTC_GAMMA.txt
Labels: documentation

#133 Update metadata templates
  hyp3_rtc_gamma/etc/README_RTC_GAMMA.txt
Labels: documentation, tools-bot

#134 Update metadata templates
  hyp3_rtc_gamma/etc/README_RTC_GAMMA.txt
Labels: documentation, tools-bot

#129 Release v2.1.0: new product names, orbit handling
  .github/PULL_REQUEST_TEMPLATE/release.md
  .github/workflows/test-and-build.yml
  .gitignore
  CHANGELOG.md
  Dockerfile
  conda-env.yml
  hyp3_rtc_gamma/__main__.py
  hyp3_rtc_gamma/etc/README_RTC_GAMMA.txt
  hyp3_rtc_gamma/etc/RTC_GAMMA_Template.xml
  hyp3_rtc_gamma/rtc_sentinel.py
  setup.py
  tests/test_rtc_sentinel.py
  tests/test_v1.py
  tests/test_v2.py
Labels: enhancement, minor
