Repository ASFHyP3/hyp3-gamma, pull requests merged in 2021-07, with the labels that each got.

#285 Release: 4.6.1
  .github/CODEOWNERS
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE/release.md
  .github/pull_request_template.md
  .github/queries/associated-pr.query.yml
  .github/workflows/changelog.yml
  .github/workflows/labeled-pr.yml
  .github/workflows/release.yml
  .github/workflows/static-analysis.yml
  .github/workflows/tag-version.yml
  .github/workflows/test-and-build.yml
  .trufflehog.txt
  CHANGELOG.md
  LICENSE
  README.md
  environment.yml
  hyp3_gamma/__init__.py
  setup.py
Labels: patch

#288 Fix incorrect hyp3-gamma version in container
  .github/workflows/test-and-build.yml
Labels: bug, bumpless

#291 do not add nodata value to the dem.tif
  hyp3_gamma/dem.py
  hyp3_gamma/insar/getDemFileGamma.py
Labels: bumpless

#293 Water mask refactor
  hyp3_gamma/dem.py
  hyp3_gamma/insar/ifm_sentinel.py
  hyp3_gamma/insar/unwrapping_geocoding.py
  hyp3_gamma/insar/water_mask.py
  hyp3_gamma/water_mask.py
  setup.py
  tests/test_entrypoints.py
  tests/test_water_mask.py
Labels: bumpless

#292 set metadata AERA_OR_POINT to "Point" for the water_mask.tif
  hyp3_gamma/insar/water_mask.py
Labels: bumpless

#296 set OGR_ENABLE_PARTIAL_REPROJECTION=TRUE in create_water_mask
  hyp3_gamma/water_mask.py
Labels: bumpless

#297 use geopandas to subset shapefile prior to creating water mask
  Dockerfile
  environment.yml
  hyp3_gamma/water_mask.py
  setup.py
Labels: bumpless

#298 remove pandas==0.23 install from dockerfile
  Dockerfile
Labels: bumpless

#299 split granule extent on antimeridian before subsetting global shapefile
  hyp3_gamma/water_mask.py
  tests/test_dem.py
  tests/test_water_mask.py
Labels: bumpless

#295 Release v4.6.2
  .github/workflows/test-and-build.yml
  CHANGELOG.md
  Dockerfile
  environment.yml
  hyp3_gamma/insar/ifm_sentinel.py
  hyp3_gamma/water_mask.py
  setup.py
  tests/data/water_mask_input.tif
  tests/test_dem.py
  tests/test_water_mask.py
Labels: patch

#289 implement the code to produce the inc_ellipsoidal_angle
  CHANGELOG.md
  environment.yml
  hyp3_gamma/insar/ifm_sentinel.py
  hyp3_gamma/insar/unwrapping_geocoding.py
  setup.py
Labels: bumpless
