Repository ASFHyP3/hyp3-gamma, pull requests merged in 2021-09, with the labels that each got.

#312 fix fringes in unw_phase browse image
  hyp3_gamma/insar/unwrapping_geocoding.py
Labels: bumpless

#314 Release GAMMA 20210701 Upgrade
  .github/workflows/test-and-build.yml
  CHANGELOG.md
  Dockerfile
  README.md
  environment.yml
  hyp3_gamma/__init__.py
  hyp3_gamma/insar/ifm_sentinel.py
  hyp3_gamma/insar/interf_pwr_s1_lt_tops_proc.py
  hyp3_gamma/insar/unwrapping_geocoding.py
  setup.py
Labels: minor

#319 Update URL for Copernicus DEM
  CHANGELOG.md
  hyp3_gamma/metadata/templates/dem/dem-cop.xml.j2
  hyp3_gamma/metadata/templates/insar/dem.xml.j2
  hyp3_gamma/metadata/templates/insar/inc_map_ell_tif.xml.j2
  hyp3_gamma/metadata/templates/insar/inc_map_tif.xml.j2
  hyp3_gamma/metadata/templates/insar/insar_dem.xml.j2
  hyp3_gamma/metadata/templates/insar/readme.md.txt.j2
  hyp3_gamma/metadata/templates/macros.j2
Labels: documentation, bumpless

#313 change include_los_displacement to include_displacement_maps, use thi…
  CHANGELOG.md
  hyp3_gamma/__main__.py
  hyp3_gamma/insar/ifm_sentinel.py
  hyp3_gamma/insar/unwrapping_geocoding.py
  tests/test_entrypoints.py
Labels: bumpless

#321 Release displacement maps
  CHANGELOG.md
  hyp3_gamma/__main__.py
  hyp3_gamma/insar/ifm_sentinel.py
  hyp3_gamma/insar/unwrapping_geocoding.py
  hyp3_gamma/metadata/templates/dem/dem-cop.xml.j2
  hyp3_gamma/metadata/templates/insar/dem.xml.j2
  hyp3_gamma/metadata/templates/insar/inc_map_ell_tif.xml.j2
  hyp3_gamma/metadata/templates/insar/inc_map_tif.xml.j2
  hyp3_gamma/metadata/templates/insar/insar_dem.xml.j2
  hyp3_gamma/metadata/templates/insar/los_disp_tif.xml.j2
  hyp3_gamma/metadata/templates/insar/lv_theta_tif.xml.j2
  hyp3_gamma/metadata/templates/insar/readme.md.txt.j2
  hyp3_gamma/metadata/templates/insar/unw_phase_tif.xml.j2
  hyp3_gamma/metadata/templates/insar/vert_disp_tif.xml.j2
  hyp3_gamma/metadata/templates/macros.j2
  tests/test_entrypoints.py
Labels: major
