Repository ASFHyP3/hyp3-gamma, pull requests merged in 2021-06, with the labels that each got.

#268 add conda to path so that __main__.py can invoke it through subprocess
  Dockerfile
Labels: bumpless

#271 remove safe off of the reference granule in metadata
  hyp3_gamma/insar/ifm_sentinel.py
Labels: bumpless

#277 Update release.yml
  .github/workflows/release.yml
Labels: CI/CD, bumpless

#278 Release metadata upgrade, dB scale, and watermap entrypoint
  .github/workflows/release.yml
  .github/workflows/test-and-build.yml
  CHANGELOG.md
  Dockerfile
  conda-env.yml
  hyp3_gamma/__main__.py
  hyp3_gamma/insar/create_metadata_insar_gamma.py
  hyp3_gamma/insar/etc/README_InSAR_GAMMA.txt
  hyp3_gamma/insar/etc/__init__.py
  hyp3_gamma/insar/ifm_sentinel.py
  hyp3_gamma/rtc/rtc_sentinel.py
  setup.py
Labels: minor

#280 Master --> main
  .github/pull_request_template.md
  .github/workflows/changelog.yml
  .github/workflows/labeled-pr.yml
  .github/workflows/release.yml
  .github/workflows/test-and-build.yml
Labels: bumpless

#281 CI/CD update, community updates, other tweaks
  .github/CODEOWNERS
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE/release.md
  .github/pull_request_template.md
  .github/queries/associated-pr.query.yml
  .github/workflows/changelog.yml
  .github/workflows/release.yml
  .github/workflows/static-analysis.yml
  .github/workflows/tag-version.yml
  .github/workflows/test-and-build.yml
  .trufflehog.txt
  CHANGELOG.md
  LICENSE
  README.md
  environment.yml
  hyp3_gamma/__init__.py
  setup.py
Labels: CI/CD
