Repository ASFHyP3/hyp3-gamma, pull requests merged in 2022-09, with the labels that each got.

#396 Release v5.5.0
  .github/workflows/test-and-build.yml
  CHANGELOG.md
  Dockerfile
Labels: minor

#397 Add S1B end of mission info
  CHANGELOG.md
  hyp3_gamma/metadata/templates/browse/browse-color.xml.j2
  hyp3_gamma/metadata/templates/browse/browse-greyscale.xml.j2
  hyp3_gamma/metadata/templates/dem/dem-cop.xml.j2
  hyp3_gamma/metadata/templates/dem/dem-eu.xml.j2
  hyp3_gamma/metadata/templates/dem/dem-gimp.xml.j2
  hyp3_gamma/metadata/templates/dem/dem-ifsar.xml.j2
  hyp3_gamma/metadata/templates/dem/dem-ned.xml.j2
  hyp3_gamma/metadata/templates/dem/dem-rema.xml.j2
  hyp3_gamma/metadata/templates/dem/dem-srtm.xml.j2
  hyp3_gamma/metadata/templates/insar/amp_tif.xml.j2
  hyp3_gamma/metadata/templates/insar/color_phase_png.xml.j2
  hyp3_gamma/metadata/templates/insar/corr_tif.xml.j2
  hyp3_gamma/metadata/templates/insar/dem.xml.j2
  hyp3_gamma/metadata/templates/insar/inc_map_ell_tif.xml.j2
  hyp3_gamma/metadata/templates/insar/inc_map_tif.xml.j2
  hyp3_gamma/metadata/templates/insar/insar_dem.xml.j2
  hyp3_gamma/metadata/templates/insar/los_disp_tif.xml.j2
  hyp3_gamma/metadata/templates/insar/lv_phi_tif.xml.j2
  hyp3_gamma/metadata/templates/insar/lv_theta_tif.xml.j2
  hyp3_gamma/metadata/templates/insar/readme.md.txt.j2
  hyp3_gamma/metadata/templates/insar/unw_phase_png.xml.j2
  hyp3_gamma/metadata/templates/insar/unw_phase_tif.xml.j2
  hyp3_gamma/metadata/templates/insar/vert_disp_tif.xml.j2
  hyp3_gamma/metadata/templates/insar/water_mask_tif.xml.j2
  hyp3_gamma/metadata/templates/insar/wrapped_phase_tif.xml.j2
  hyp3_gamma/metadata/templates/rtc/area.xml.j2
  hyp3_gamma/metadata/templates/rtc/inc_map.xml.j2
  hyp3_gamma/metadata/templates/rtc/ls_map.xml.j2
  hyp3_gamma/metadata/templates/rtc/product.xml.j2
  hyp3_gamma/metadata/templates/rtc/readme.md.txt.j2
  hyp3_gamma/metadata/templates/rtc/rgb.xml.j2
Labels: documentation, patch

#399 Release v5.5.1
  CHANGELOG.md
  hyp3_gamma/metadata/templates/browse/browse-color.xml.j2
  hyp3_gamma/metadata/templates/browse/browse-greyscale.xml.j2
  hyp3_gamma/metadata/templates/dem/dem-cop.xml.j2
  hyp3_gamma/metadata/templates/dem/dem-eu.xml.j2
  hyp3_gamma/metadata/templates/dem/dem-gimp.xml.j2
  hyp3_gamma/metadata/templates/dem/dem-ifsar.xml.j2
  hyp3_gamma/metadata/templates/dem/dem-ned.xml.j2
  hyp3_gamma/metadata/templates/dem/dem-rema.xml.j2
  hyp3_gamma/metadata/templates/dem/dem-srtm.xml.j2
  hyp3_gamma/metadata/templates/insar/amp_tif.xml.j2
  hyp3_gamma/metadata/templates/insar/color_phase_png.xml.j2
  hyp3_gamma/metadata/templates/insar/corr_tif.xml.j2
  hyp3_gamma/metadata/templates/insar/dem.xml.j2
  hyp3_gamma/metadata/templates/insar/inc_map_ell_tif.xml.j2
  hyp3_gamma/metadata/templates/insar/inc_map_tif.xml.j2
  hyp3_gamma/metadata/templates/insar/insar_dem.xml.j2
  hyp3_gamma/metadata/templates/insar/los_disp_tif.xml.j2
  hyp3_gamma/metadata/templates/insar/lv_phi_tif.xml.j2
  hyp3_gamma/metadata/templates/insar/lv_theta_tif.xml.j2
  hyp3_gamma/metadata/templates/insar/readme.md.txt.j2
  hyp3_gamma/metadata/templates/insar/unw_phase_png.xml.j2
  hyp3_gamma/metadata/templates/insar/unw_phase_tif.xml.j2
  hyp3_gamma/metadata/templates/insar/vert_disp_tif.xml.j2
  hyp3_gamma/metadata/templates/insar/water_mask_tif.xml.j2
  hyp3_gamma/metadata/templates/insar/wrapped_phase_tif.xml.j2
  hyp3_gamma/metadata/templates/rtc/area.xml.j2
  hyp3_gamma/metadata/templates/rtc/inc_map.xml.j2
  hyp3_gamma/metadata/templates/rtc/ls_map.xml.j2
  hyp3_gamma/metadata/templates/rtc/product.xml.j2
  hyp3_gamma/metadata/templates/rtc/readme.md.txt.j2
  hyp3_gamma/metadata/templates/rtc/rgb.xml.j2
Labels: patch

#401 set OGR_GEOJSON_MAX_OBJ_SIZE in create_water_map
  hyp3_gamma/water_mask.py
Labels: bug, bumpless

#402 set OGR_ENABLE_PARTIAL_REPROJECTION=YES in create_water_map
  hyp3_gamma/water_mask.py
Labels: bumpless

#403 Release v5.6.0
  CHANGELOG.md
  hyp3_gamma/metadata/templates/insar/los_disp_tif.xml.j2
  hyp3_gamma/metadata/templates/insar/readme.md.txt.j2
  hyp3_gamma/metadata/templates/insar/unw_phase_png.xml.j2
  hyp3_gamma/metadata/templates/insar/unw_phase_tif.xml.j2
  hyp3_gamma/metadata/templates/insar/vert_disp_tif.xml.j2
  hyp3_gamma/metadata/templates/insar/water_mask_tif.xml.j2
  hyp3_gamma/water_mask.py
  tests/data/water_mask_input.tif
  tests/test_water_mask.py
Labels: patch
