Repository ASFHyP3/hyp3-gamma, pull requests merged in 2022-12, with the labels that each got.

#422 move lxml and hyp3lib to pip installs to fix #421
  CHANGELOG.md
  environment.yml
Labels: bug

#424 Release v5.7.2
  CHANGELOG.md
  Dockerfile
  environment.yml
Labels: patch

#425 add decibel in the README.md.txt when the product is with decibel option
  CHANGELOG.md
  hyp3_gamma/metadata/rtc.py
  tests/metadata/test_rtc_gamma.py
Labels: patch

#427 update rtc metadata documenting very dark power/amp/db images
  hyp3_gamma/metadata/templates/rtc/product.xml.j2
Labels: bumpless

#426 Release 5.7.3 - add decibel option
  CHANGELOG.md
  hyp3_gamma/metadata/rtc.py
  hyp3_gamma/metadata/templates/rtc/product.xml.j2
  tests/metadata/test_rtc_gamma.py
Labels: patch
