Repository ASFHyP3/hyp3-gamma, pull requests merged in 2022-10, with the labels that each got.

#400 Update base Ubuntu image to 22.04 for docker
  .github/workflows/test-and-build.yml
  CHANGELOG.md
  Dockerfile
  environment.yml
  setup.py
Labels: minor

#407 Release v5.7.0 -- Ubuntu 22.04 upgrade
  .github/workflows/test-and-build.yml
  CHANGELOG.md
  Dockerfile
  environment.yml
  setup.py
Labels: minor

#409 automate version updates for github actions
  .github/dependabot.yml
  .github/workflows/changelog.yml
  .github/workflows/labeled-pr.yml
  .github/workflows/release.yml
  .github/workflows/static-analysis.yml
  .github/workflows/tag-version.yml
  .github/workflows/test-and-build.yml
Labels: bumpless

#410 Fix dependabot
  .github/dependabot.yml
Labels: bumpless, CI/CD
