Repository ASFHyP3/hyp3-gamma, pull requests merged in 2022-02, with the labels that each got.

#340 upgrade pip and pin numpy version to match system ubuntu version
  Dockerfile
  environment.yml
  setup.py
Labels: bumpless

#342 fetch tags for in-docker package build
  .github/workflows/test-and-build.yml
Labels: bug, bumpless

#341 Encrypt Earthdata Login Information
  .github/queries/associated-pr.query.yml
  .github/queries/pr-labels.query.yml
  .github/workflows/changelog.yml
  .github/workflows/labeled-pr.yml
  .github/workflows/release.yml
  .github/workflows/static-analysis.yml
  .github/workflows/tag-version.yml
  .github/workflows/test-and-build.yml
  CHANGELOG.md
  Dockerfile
  environment.yml
  hyp3_gamma/__main__.py
  setup.py
Labels: patch

#344 Fix changelog syntax
  CHANGELOG.md
Labels: bug, bumpless

#348 Release v5.1.4 - us-west-2 dem
  CHANGELOG.md
  hyp3_gamma/dem.py
  tests/test_dem.py
Labels: patch
