Repository ASFHyP3/hyp3-gamma, pull requests merged in 2022-06, with the labels that each got.

#375 Replaced updated with changed in changelog
  CHANGELOG.md
Labels: bumpless

#374 Update-DEM
  CHANGELOG.md
  hyp3_gamma/dem.py
  tests/test_dem.py
Labels: minor

#376 Update metadata templates
  CHANGELOG.md
  hyp3_gamma/metadata/templates/insar/readme.md.txt.j2
  hyp3_gamma/metadata/templates/insar/unw_phase_png.xml.j2
  hyp3_gamma/metadata/templates/rtc/readme.md.txt.j2
Labels: documentation, patch

#377 Release v5.4.1
  CHANGELOG.md
  hyp3_gamma/metadata/templates/insar/readme.md.txt.j2
  hyp3_gamma/metadata/templates/insar/unw_phase_png.xml.j2
  hyp3_gamma/metadata/templates/rtc/readme.md.txt.j2
Labels: patch
