Repository ASFHyP3/hyp3-gamma, pull requests merged in 2023-02, with the labels that each got.

#437 remove water_map entrypoint from setup.py
  setup.py
Labels: bumpless

#438 Release v6.0.0
  CHANGELOG.md
  Dockerfile
  hyp3_gamma/__main__.py
  setup.py
Labels: major

#443 Release v6.0.1-- fixing broken Copernicus GLO-30 DEM links in product metadata
  .github/workflows/test-and-build.yml
  CHANGELOG.md
  hyp3_gamma/metadata/templates/dem/dem-cop.xml.j2
  hyp3_gamma/metadata/templates/insar/dem.xml.j2
  hyp3_gamma/metadata/templates/insar/inc_map_tif.xml.j2
  hyp3_gamma/metadata/templates/insar/insar_dem.xml.j2
  hyp3_gamma/metadata/templates/insar/readme.md.txt.j2
  hyp3_gamma/metadata/templates/macros.j2
Labels: patch
