Repository ASFHyP3/hyp3-gamma, pull requests merged in 2023-11, with the labels that each got.

#511 add shapely>=2.0 in the setup.py and environment.yml
  hyp3_gamma/water_mask.py
Labels: bumpless

#512 need to add libspatialindex-dev and rtree for making the geopandas.cl…
  Dockerfile
  environment.yml
  setup.py
Labels: bumpless

#514 back to the previous way of reasding the mask with geopandas.read_fil…
  Dockerfile
  hyp3_gamma/water_mask.py
Labels: bumpless

#515 Fix Errors in Water Masking
  hyp3_gamma/water_mask.py
Labels: bumpless

#516 do not split the antimeridian extent, but convert it into UTM, then d…
  hyp3_gamma/water_mask.py
  tests/test_water_mask.py
Labels: bumpless

#518 Removed Unnecessary Imports
  environment.yml
  setup.py
Labels: bumpless

#519 Docstring Fix
  hyp3_gamma/water_mask.py
Labels: documentation, bumpless

#520 Better Changelog for Release 6.4.1
  CHANGELOG.md
Labels: bumpless

#517 Release 6.4.1
  .github/workflows/test-and-build.yml
  CHANGELOG.md
  environment.yml
  hyp3_gamma/water_mask.py
  setup.py
  tests/test_water_mask.py
Labels: patch

#521 Temporarily pin `hyp3lib` to `develop` branch
  environment.yml
Labels: bumpless

#523 Use the new orbit fetching interface
  hyp3_gamma/insar/ifm_sentinel.py
  hyp3_gamma/rtc/rtc_sentinel.py
Labels: bumpless

#524 Pin to `hyp3lib` `develop` in `setup.py`
  environment.yml
  setup.py
Labels: bumpless

#525 Release v7.0.0
  CHANGELOG.md
  README.md
  environment.yml
  hyp3_gamma/__main__.py
  hyp3_gamma/insar/ifm_sentinel.py
  hyp3_gamma/rtc/rtc_sentinel.py
  setup.py
Labels: major

#531 add buffer 0.15 to original extent in WGS84 and clip in WGS84
  hyp3_gamma/water_mask.py
Labels: bumpless

#533 Updated Chagelog
  CHANGELOG.md
  tests/test_water_mask.py
Labels: patch

#532 Release 7.0.1
  CHANGELOG.md
  hyp3_gamma/water_mask.py
  tests/test_water_mask.py
Labels: patch
