Repository ASFHyP3/hyp3-gamma, pull requests merged in 2023-05, with the labels that each got.

#452 Release V6.2.0
  .github/workflows/changelog.yml
  .github/workflows/labeled-pr.yml
  .github/workflows/release.yml
  .github/workflows/static-analysis.yml
  .github/workflows/tag-version.yml
  .github/workflows/test-and-build.yml
  CHANGELOG.md
  hyp3_gamma/__main__.py
  hyp3_gamma/metadata/templates/rtc/readme.md.txt.j2
Labels: minor

#454 Remove references to standard products from the RTC metadata
  CHANGELOG.md
  hyp3_gamma/metadata/templates/rtc/readme.md.txt.j2
Labels: documentation, patch

#456 add release checklist workflow
  .github/PULL_REQUEST_TEMPLATE/release.md
  .github/workflows/release-template-comment.yml
Labels: bumpless

#457 Release v6.2.1 - Update RTC readme
  .github/PULL_REQUEST_TEMPLATE/release.md
  .github/workflows/release-template-comment.yml
  CHANGELOG.md
  hyp3_gamma/metadata/templates/rtc/readme.md.txt.j2
Labels: documentation, patch

#458 Drop unneeded default pull request template
  .github/pull_request_template.md
Labels: bumpless

#460 Update job name in release checklist workflow
  .github/workflows/release-template-comment.yml
Labels: bumpless, CI/CD
