Repository ASFHyP3/hyp3-gamma, pull requests merged in 2024-02, with the labels that each got.

#542 Updated Water Masking with OSM and WorldCover
  CHANGELOG.md
  hyp3_gamma/metadata/templates/insar/water_mask_tif.xml.j2
  hyp3_gamma/water_mask.py
  tests/data/water_mask_output_info.txt
  tests/test_water_mask.py
Labels: minor

#543 New Cropping Method for the New Water Masks
  hyp3_gamma/water_mask.py
  tests/data/water_mask_output_info.txt
Labels: bumpless

#545 Fix Changelog Number
  CHANGELOG.md
Labels: bumpless

#544 Release 8.1.0
  .github/workflows/changelog.yml
  .github/workflows/create-jira-issue.yml
  .github/workflows/labeled-pr.yml
  .github/workflows/release-template-comment.yml
  .github/workflows/release.yml
  .github/workflows/static-analysis.yml
  .github/workflows/tag-version.yml
  .github/workflows/test-and-build.yml
  .trufflehog.txt
  CHANGELOG.md
  hyp3_gamma/metadata/templates/insar/water_mask_tif.xml.j2
  hyp3_gamma/water_mask.py
  tests/data/water_mask_output_info.txt
  tests/test_water_mask.py
Labels: minor

#548 Release v8.1.1
  CHANGELOG.md
  hyp3_gamma/metadata/templates/insar/readme.md.txt.j2
  hyp3_gamma/metadata/templates/insar/water_mask_tif.xml.j2
Labels: patch

#550 fix malformed arguments to subprocess.run
  hyp3_gamma/water_mask.py
Labels: bumpless

#552 Release v8.1.2
  CHANGELOG.md
  hyp3_gamma/metadata/templates/insar/readme.md.txt.j2
  hyp3_gamma/metadata/templates/insar/water_mask_tif.xml.j2
  hyp3_gamma/metadata/templates/insar/wrapped_phase_tif.xml.j2
  hyp3_gamma/water_mask.py
Labels: patch
