Repository ASFHyP3/hyp3-gamma, pull requests merged in 2025-05, with the labels that each got.

#636 Add code from hyp3-lib
  CHANGELOG.md
  hyp3_gamma/get_gamma_version.py
  hyp3_gamma/get_parameter.py
  hyp3_gamma/insar/ifm_sentinel.py
  hyp3_gamma/insar/interf_pwr_s1_lt_tops_proc.py
  hyp3_gamma/insar/par_s1_slc_single.py
  hyp3_gamma/insar/slc_copy_s1_full_sw.py
  hyp3_gamma/insar/unwrapping_geocoding.py
  hyp3_gamma/make_asf_browse.py
  hyp3_gamma/rtc/byte_sigma_scale.py
  hyp3_gamma/rtc/coregistration.py
  hyp3_gamma/rtc/gdal_file.py
  hyp3_gamma/rtc/make_cogs.py
  hyp3_gamma/rtc/raster_boundary_to_shape.py
  hyp3_gamma/rtc/rtc_sentinel.py
  tests/conftest.py
  tests/rtc/test_make_cogs.py
  tests/test_entrypoints.py
  tests/test_get_gamma_version.py
  tests/test_make_asf_browse.py
Labels: patch

#638 Add create amp
  hyp3_gamma/rtc/create_amp.py
  hyp3_gamma/rtc/rtc_sentinel.py
Labels: bumpless

#639 Update hyp3lib to version 4
  CHANGELOG.md
  requirements.txt
Labels: bumpless

#645 Release v9.0.6
  .github/workflows/changelog.yml
  .github/workflows/create-jira-issue.yml
  .github/workflows/labeled-pr.yml
  .github/workflows/release-template-comment.yml
  .github/workflows/release.yml
  .github/workflows/static-analysis.yml
  .github/workflows/tag-version.yml
  .github/workflows/test-and-build.yml
  CHANGELOG.md
  hyp3_gamma/dem.py
  requirements-develop.txt
  tests/data/far-north.kml
  tests/data/south-pole.kml
  tests/test_dem.py
Labels: bug, patch
